- hosts: all
  gather_facts: false
  connection: local
  vars:
    data: "{{ lookup('file', 'data/1.txt') | split('\n\n') | map('split', '\n') | map('map','int') }}"
  tasks:
    - name: part 1
      debug: msg="{{ data | map('sum') | max }}"
    - name: part 2
      debug: msg="{{ (data | map('sum') | sort )[-3:] | sum }}"
